/* Academy mini-workshop. Original exercises; no network writes, credentials or SEVER access. */
(()=>{'use strict';
const STORE='academy-skills-practice-v1';
const $=id=>document.getElementById(id);
const english=[
 {title:'I am — представляемся',goal:'Могу коротко представиться по-английски.',theory:'I am означает «я ...». В речи I am часто сокращают до I’m. Перед названием профессии в единственном числе обычно нужен a/an: a tester, a student.',example:'I am a tester. — Я тестировщик.',speak:'I am a tester.',prompt:'Напиши по-английски: «Я тестировщик».',answers:['i am a tester',"i'm a tester"],transfer:'Другая ситуация: напиши «Я студент».',transferAnswers:['i am a student',"i'm a student"],hint:'Начни с I am. Для профессии или роли добавь a.',explain:'I am + a + роль. Сокращение I’m тоже подходит.'},
 {title:'There is / there are',goal:'Могу сказать, сколько проблем заметил.',theory:'There is используется с одной вещью, there are — с несколькими. Сравни «одна ошибка» и «две ошибки»: единственное и множественное число.',example:'There is a bug. — Есть одна ошибка.',speak:'There is a bug.',prompt:'Напиши: «Есть одна ошибка».',answers:['there is a bug',"there's a bug"],transfer:'Другая ситуация: напиши «Есть две ошибки».',transferAnswers:['there are two bugs'],hint:'Для одной ошибки используй there is, для двух — there are.',explain:'One bug → there is a bug; two bugs → there are two bugs.'},
 {title:'Короткая инструкция: click',goal:'Могу дать простую инструкцию для воспроизведения.',theory:'Повелительное предложение начинается с глагола без I или you: Click, Open, Enter. Названия кнопок в шагах можно писать с большой буквы.',example:'Click Save. — Нажми «Сохранить».',speak:'Click Save.',prompt:'Напиши инструкцию «Нажми Save».',answers:['click save','click the save button'],transfer:'Теперь другая команда: «Открой страницу».',transferAnswers:['open the page'],hint:'Начни сразу с действия: Click ... или Open ...',explain:'В инструкции глагол ставится в начале: Click Save / Open the page.'},
 {title:'Сообщаем о проблеме',goal:'Могу составить простое сообщение о неработающей функции.',theory:'В настоящем времени с подлежащим the button отрицание образуется does not + начальная форма глагола. Говорим does not work, а не does not works.',example:'The button does not work. — Кнопка не работает.',speak:'The button does not work.',prompt:'Напиши «Кнопка не работает».',answers:['the button does not work',"the button doesn't work"],transfer:'Скажи иначе: «Форма не работает».',transferAnswers:['the form does not work',"the form doesn't work"],hint:'The button + does not + work. После does not глагол не меняется.',explain:'The button does not work; меняем button на form для другой ситуации.'}
];
const python=[
 {title:'Строки: убираем лишние пробелы',goal:'Могу создать функцию и работать со строкой.',theory:'Функция принимает значение через параметр и возвращает результат оператором return. Метод strip() удаляет пробелы по краям строки; исходную строку не меняет.',example:'text = "  QA  "\nprint(text.strip())  # QA',task:'Напиши clean_title(title), которая возвращает заголовок без пробелов по краям. Не печатай результат внутри функции: используй return.',starter:'def clean_title(title):\n    # Верни строку без пробелов по краям\n    pass',hint:'Для строки title вызови метод .strip() и верни результат через return.',fn:'clean_title',cases:[{args:['  QA  '],expected:'QA'},{args:['Bug report'],expected:'Bug report'},{args:['   '],expected:''},{args:[' x '],expected:'x'}]},
 {title:'Условия: проверяем границы',goal:'Могу превратить требование в логическое условие.',theory:'Сначала очисти заголовок от пробелов; затем проверь, что длина от 1 до 20 включительно. len() даёт длину строки, условие 1 <= n <= 20 возвращает True или False.',example:'n = len("Test")\nprint(1 <= n <= 20)  # True',task:'Напиши valid_title(title). Возвращай True, если после strip() длина от 1 до 20; в остальных случаях False. Проверь граничные случаи.',starter:'def valid_title(title):\n    # Очисти пробелы, проверь обе границы\n    pass',hint:'Сохрани len(title.strip()) в переменную n. Верни сравнение 1 <= n <= 20.',fn:'valid_title',cases:[{args:[''],expected:false},{args:[' '],expected:false},{args:['A'],expected:true},{args:['x'.repeat(20)],expected:true},{args:['x'.repeat(21)],expected:false},{args:['  OK  '],expected:true}]},
 {title:'Условие: PASS или FAIL',goal:'Могу сравнить ожидаемый и фактический результаты.',theory:'Тест PASS, когда факт точно совпадает с ожиданием. Для сравнения значений используй ==, не =. Нельзя объявлять тест успешным только потому, что программа запустилась.',example:'expected = "saved"\nactual = "saved"\nprint(expected == actual)  # True',task:'Напиши test_result(expected, actual). Верни строку "PASS" при совпадении значений, иначе "FAIL". Сравнение должно учитывать регистр.',starter:'def test_result(expected, actual):\n    # Сравни значения и верни строку\n    pass',hint:'Используй if expected == actual: и верни "PASS"; иначе "FAIL".',fn:'test_result',cases:[{args:['saved','saved'],expected:'PASS'},{args:['saved','error'],expected:'FAIL'},{args:['PASS','pass'],expected:'FAIL'},{args:['',''],expected:'PASS'}]},
 {title:'Список и цикл: считаем провалы',goal:'Могу пройти по результатам проверок и посчитать ошибки.',theory:'Список хранит несколько значений. Цикл for перебирает элементы. Заведи счётчик 0 и увеличивай его при значении "FAIL". Есть и другие способы, но сначала разберись с циклом.',example:'results = ["PASS", "FAIL"]\nfor item in results:\n    print(item)',task:'Напиши count_failed(results), возвращающую количество элементов, которые точно равны "FAIL". Пустой список даёт 0.',starter:'def count_failed(results):\n    # Пройди циклом по списку и верни количество FAIL\n    pass',hint:'Создай counter = 0. В цикле for item in results увеличивай счётчик, если item == "FAIL". Верни counter.',fn:'count_failed',cases:[{args:[[]],expected:0},{args:[['PASS']],expected:0},{args:[['FAIL','PASS','FAIL']],expected:2},{args:[['FAIL','fail','PASS']],expected:1},{args:[['FAIL','FAIL','FAIL']],expected:3}]}
];
let saved={english:{},python:{}},storageOk=true,enIdx=0,enHint=false,enFirst=false,enPassed=false,pyIdx=0,pyHint=false,worker=null,ready=false,busy=false,pending=null,seq=0;
function load(){try{const raw=localStorage.getItem(STORE);if(!raw)return;const data=JSON.parse(raw);if(data?.version===1&&data.english&&data.python&&typeof data.english==='object'&&typeof data.python==='object')saved={english:data.english,python:data.python};}catch{storageOk=false;}}
function persist(){if(!storageOk)return;try{localStorage.setItem(STORE,JSON.stringify({version:1,english:saved.english,python:saved.python}));}catch{storageOk=false;}}
function mark(track,index){saved[track][String(index)]=new Date().toISOString();persist();updateCounters();}
function updateCounters(){for(const [track,items] of [['english',english],['python',python]]){const count=items.filter((_,i)=>saved[track][String(i)]).length;$(track+'Count').textContent=`${count} / ${items.length} · ${storageOk?'в этом браузере':'без сохранения'}`;for(const option of $(track+'Pick').options){const n=Number(option.value);option.textContent=`${n+1}. ${items[n].title}${saved[track][String(n)]?' · выполнено':''}`;}}}
function normalize(value){return value.toLowerCase().trim().replace(/[’‘]/g,"'").replace(/[.!?]+$/g,'').replace(/\s+/g,' ');}
function selectEnglish(index){enIdx=index;enHint=false;enFirst=false;enPassed=false;const item=english[index];$('englishPick').value=String(index);$('englishTopic').textContent=item.title;$('englishGoal').textContent=`После упражнения: ${item.goal}`;$('englishTheory').textContent=item.theory;$('englishExample').textContent=item.example;$('englishPrompt').textContent=item.prompt;$('englishTransferPrompt').textContent=item.transfer;$('englishAnswer').value='';$('englishSecond').value='';$('englishFeedback').textContent='';$('englishTransferFeedback').textContent='';$('englishTransfer').hidden=true;$('englishNext').hidden=true;$('englishCheck').disabled=false;$('englishHint').disabled=false;updateCounters();}
function checkFirst(){if(enFirst)return;const value=normalize($('englishAnswer').value),item=english[enIdx];if(!value){$('englishFeedback').textContent='Сначала напиши свою фразу.';return;}if(!item.answers.includes(value)){$('englishFeedback').textContent=`Пока не совпало. ${item.explain} Исправь и попробуй ещё раз.`;return;}enFirst=true;$('englishCheck').disabled=true;$('englishFeedback').textContent=`✓ Фраза верна. ${item.explain} Теперь примени правило к другому примеру.`;$('englishTransfer').hidden=false;$('englishSecond').focus();}
function checkTransfer(){if(!enFirst||enPassed)return;const value=normalize($('englishSecond').value),item=english[enIdx];if(!value){$('englishTransferFeedback').textContent='Напиши вторую фразу самостоятельно.';return;}if(!item.transferAnswers.includes(value)){$('englishTransferFeedback').textContent='Пока не совпало. Сравни структуру с первым примером, исправь фразу и попробуй снова.';return;}enPassed=true;$('englishTransferCheck').disabled=true;$('englishTransferFeedback').textContent=enHint?'✓ Обе фразы верны. Была подсказка: вернись к теме позже и попробуй без неё. Отметка самостоятельности не добавлена.':'✓ Обе фразы верны без подсказки. Зафиксировано только письменное упражнение — не уровень английского.';if(!enHint)mark('english',enIdx);$('englishNext').hidden=false;}
function selectPython(index){pyIdx=index;pyHint=false;const item=python[index];$('pythonPick').value=String(index);$('pythonTopic').textContent=item.title;$('pythonGoal').textContent=`После упражнения: ${item.goal}`;$('pythonTheory').textContent=item.theory;$('pythonExample').textContent=item.example;$('pythonTask').textContent=item.task;$('pythonEditor').value=item.starter;$('pythonStatus').textContent='Напиши функцию, затем запусти код на нескольких тестах.';$('pythonOutput').textContent='';$('pythonNext').hidden=true;$('pythonRun').disabled=busy;updateCounters();}
function hintEnglish(){enHint=true;$('englishFeedback').textContent=english[enIdx].hint;$('englishHint').disabled=true;}
function hintPython(){pyHint=true;$('pythonStatus').textContent=python[pyIdx].hint;$('pythonHint').disabled=true;}
function harness(item,code){const cases=JSON.stringify(item.cases);const fn=item.fn;return `${code}\nimport json as _ac_json\n_ac_cases = _ac_json.loads(${JSON.stringify(cases)})\n_ac_outcomes = []\nfor _ac_case in _ac_cases:\n    try:\n        _ac_got = ${fn}(*_ac_case['args'])\n        _ac_outcomes.append({'ok': type(_ac_got) == type(_ac_case['expected']) and _ac_got == _ac_case['expected'], 'input': repr(_ac_case['args'])[:120], 'expected': repr(_ac_case['expected'])[:120], 'actual': repr(_ac_got)[:120]})\n    except Exception as _ac_exc:\n        _ac_outcomes.append({'ok': False, 'input': repr(_ac_case['args'])[:120], 'expected': repr(_ac_case['expected'])[:120], 'actual': type(_ac_exc).__name__ + ': ' + str(_ac_exc)[:90]})\nprint('__ACADEMY_CHECK__' + _ac_json.dumps(_ac_outcomes,ensure_ascii=False))`;
}
function finishRun(message){busy=false;pending=null;$('pythonRun').disabled=false;$('pythonStatus').textContent=message;}
function workerMessage(event){const data=event.data||{};if(data.type==='ready'){ready=true;if(pending)worker.postMessage({id:pending.id,code:pending.code});return;}if(data.type==='load-error'){finishRun('Не удалось загрузить Python. Проверь интернет и попробуй позднее.');worker?.terminate();worker=null;ready=false;return;}if(data.type!=='result'||!pending||data.id!==pending.id)return;const {index,hinted}=pending;const output=String(data.output||'');const pos=output.lastIndexOf('__ACADEMY_CHECK__');if(!data.ok||pos<0){$('pythonOutput').textContent=output.slice(0,1600)||'Выполнение не удалось.';finishRun('Код не выполнился до конца. Проверь синтаксис, название функции и отступы.');return;}let checks;try{checks=JSON.parse(output.slice(pos+'__ACADEMY_CHECK__'.length).trim());if(!Array.isArray(checks)||checks.length!==python[index].cases.length)throw Error('Invalid test report');}catch{$('pythonOutput').textContent='Невозможно прочитать результаты; попробуй ещё раз.';finishRun('Проверка не завершена.');return;}const passed=checks.filter(c=>c.ok).length;$('pythonOutput').textContent=checks.map((c,i)=>`${c.ok?'✓':'✗'} Тест ${i+1}: вход ${c.input}\n  Ожидалось: ${c.expected}\n  Получено: ${c.actual}`).join('\n\n');if(passed===checks.length){if(!hinted)mark('python',index);$('pythonNext').hidden=false;finishRun(hinted?`✓ ${passed}/${checks.length} проверок прошли. Ты использовал подсказку: повтори без неё для отметки самостоятельности.`:`✓ ${passed}/${checks.length} проверок прошли самостоятельно. Это результат данных тестов, не доказательство отсутствия всех ошибок.`);}else finishRun(`Пройдено ${passed} из ${checks.length}. Исправь ошибку и запусти снова — особенно проверь границы.`);}
function runPython(){if(busy)return;const code=$('pythonEditor').value.trim();if(!code||code.length>9000){$('pythonStatus').textContent='Напиши функцию (до 9000 символов).';return;}busy=true;$('pythonRun').disabled=true;$('pythonOutput').textContent='';$('pythonStatus').textContent='Загружаем Python и выполняем проверки. Первый запуск может занять время.';const item=python[pyIdx],id=++seq;pending={id,index:pyIdx,hinted:pyHint,code:harness(item,code)};try{if(!worker){ready=false;worker=new Worker('python-worker.mjs',{type:'module'});worker.onmessage=workerMessage;worker.onerror=()=>{finishRun('Не удалось запустить Python. Проверь соединение.');worker?.terminate();worker=null;ready=false;};}if(ready)worker.postMessage({id,code:pending.code});}catch{finishRun('Браузер не запустил окружение Python. Можно попробовать архивную консоль.');worker?.terminate();worker=null;ready=false;}}
function init(){for(const [name,bank] of [['english',english],['python',python]]){bank.forEach((_,i)=>{const option=document.createElement('option');option.value=String(i);$(name+'Pick').append(option);});}load();selectEnglish(0);selectPython(0);$('englishPick').addEventListener('change',e=>selectEnglish(Number(e.target.value)));$('pythonPick').addEventListener('change',e=>{if(!busy)selectPython(Number(e.target.value));else $('pythonPick').value=String(pyIdx);});$('englishCheck').addEventListener('click',checkFirst);$('englishTransferCheck').addEventListener('click',checkTransfer);$('englishHint').addEventListener('click',hintEnglish);$('englishNext').addEventListener('click',()=>selectEnglish((enIdx+1)%english.length));$('englishAnswer').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();checkFirst();}});$('englishSecond').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();checkTransfer();}});$('speak').disabled=!('speechSynthesis' in window);$('speak').addEventListener('click',()=>{if(!('speechSynthesis' in window))return;try{speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(english[enIdx].speak);utterance.lang='en-US';utterance.rate=.85;speechSynthesis.speak(utterance);}catch{$('englishFeedback').textContent='В этом браузере озвучивание недоступно.';}});$('pythonRun').addEventListener('click',runPython);$('pythonHint').addEventListener('click',hintPython);$('pythonReset').addEventListener('click',()=>{if(busy)return;$('pythonEditor').value=python[pyIdx].starter;$('pythonOutput').textContent='';$('pythonStatus').textContent='Заготовка восстановлена. Напиши решение самостоятельно.';});$('pythonNext').addEventListener('click',()=>selectPython((pyIdx+1)%python.length));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();