/* Browser checks use disposable mock auth and API: no real keys, bills or user data. */
const assert=require('node:assert/strict');
const {chromium}=require('playwright');
const ROOT='http://127.0.0.1:4173/';
const GUEST=`window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:null},error:null})}})};`;
const OWNER=`window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:{access_token:'test-only-token'}},error:null}),getUser:async()=>({data:{user:{id:'test-only-owner'}},error:null})}})};`;
(async()=>{const browser=await chromium.launch({headless:true});try{
 for(const width of [1440,390,320]){
  const page=await browser.newPage({viewport:{width,height:810}}),errors=[];
  page.on('pageerror',err=>errors.push(err.message));
  await page.route('**/vendor/supabase.js',route=>route.fulfill({status:200,contentType:'text/javascript',body:GUEST}));
  await page.goto(ROOT+'ai.html?lesson=3&subject=english',{waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>document.querySelector('#aiStatus').textContent.includes('Войди'));
  assert.equal(await page.locator('#subject').inputValue(),'english');
  assert.equal(await page.locator('#lesson').inputValue(),'3');
  assert.equal(await page.locator('#send').isDisabled(),true,'Guests never reach paid API');
  assert.equal(await page.locator('.mobile-nav a').count(),4);
  assert.match(await page.locator('#aiRubricText').textContent(),/I am a student/i);
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth);
  assert.ok(overflow<=2,`${width}px: overflow ${overflow}`);
  assert.deepEqual(errors,[],`${width}px guest errors: ${errors.join('; ')}`);
  console.log(`PASS: guest tutor ${width}px, lesson rubric visible, no paid calls`);
  await page.close();
 }
 const waiting=await browser.newPage();await waiting.route('**/vendor/supabase.js',route=>route.fulfill({status:200,contentType:'text/javascript',body:OWNER}));
 await waiting.route('**/functions/v1/academy-tutor',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({configured:false})}));
 await waiting.goto(ROOT+'ai.html',{waitUntil:'domcontentloaded'});
 await waiting.waitForFunction(()=>document.querySelector('#aiStatus').textContent.includes('ACADEMY_OPENAI_API_KEY'));
 assert.equal(await waiting.locator('#send').isDisabled(),true,'No key means no fake assistant');
 console.log('PASS: missing key is explicit and does not enable chat');await waiting.close();
 const owner=await browser.newPage({viewport:{width:390,height:844}}),requests=[],errors=[];
 owner.on('pageerror',err=>errors.push(err.message));
 await owner.route('**/vendor/supabase.js',route=>route.fulfill({status:200,contentType:'text/javascript',body:OWNER}));
 await owner.route('**/functions/v1/academy-tutor',async route=>{
  if(route.request().method()==='GET')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({configured:true,model:'gpt-5.6-terra'})});
  requests.push(JSON.parse(route.request().postData()));
  await new Promise(resolve=>setTimeout(resolve,200));
  return route.fulfill(requests.length===2?{status:503,contentType:'application/json',body:JSON.stringify({message:'OpenAI временно недоступен.'})}:{status:200,contentType:'application/json',body:JSON.stringify({reply:'Указаны шаги. Пока не вижу точных тестовых данных. Что введёшь перед поиском?'})});
 });
 await owner.goto(ROOT+'ai.html?lesson=5&subject=qa&mode=review',{waitUntil:'domcontentloaded'});
 await owner.waitForFunction(()=>document.querySelector('#aiStatus').textContent.includes('Наставник подключён'));
 assert.equal(await owner.locator('#lesson').inputValue(),'5');
 assert.match(await owner.locator('#lessonTopic').textContent(),/ошибк/i);
 assert.match(await owner.locator('#aiRubricText').textContent(),/шаг/i);
 assert.equal(await owner.locator('.mode[data-mode="review"]').getAttribute('aria-pressed'),'true');
 await owner.waitForFunction(()=>document.querySelector('#returnToLesson')?.getAttribute('href')?.includes('flow=1'));
 assert.equal(await owner.locator('#returnToLesson').getAttribute('href'),'path.html?lesson=5&subject=qa&flow=1');
 assert.equal(requests.length,0,'Opening a lesson must not spend tokens');
 await owner.locator('#question').fill('Баг');await owner.locator('#send').click();
 assert.equal(requests.length,0,'Review of empty work cannot spend tokens');
 assert.match(await owner.locator('#aiStatus').textContent(),/работу/i);
 await owner.locator('#question').fill('Я проверил форму. Ожидал отказ, но она сохранила неверный адрес.');await owner.locator('#send').click();
 assert.equal(await owner.locator('#subject').isDisabled(),true,'Do not change context during response');
 await owner.waitForFunction(()=>document.querySelectorAll('.chat-message').length===2);
 assert.equal(requests.length,1);assert.equal(requests[0].mode,'review');assert.equal(requests[0].subject,'qa');assert.equal(requests[0].lesson,5);
 assert.equal(requests[0].history.length,0);
 assert.equal(Object.hasOwn(requests[0],'theory'),false,'Only identifiers, answer and short history leave browser');
 await owner.locator('#question').fill('Как оформить это в отчёт?');await owner.locator('#send').click();
 await owner.waitForFunction(()=>document.querySelectorAll('.chat-message').length===4);
 assert.equal(requests[1].history.length,2);
 assert.equal(await owner.locator('#question').inputValue(),'Как оформить это в отчёт?','Restore draft when provider fails');
 await owner.locator('#clearChat').click();assert.equal(await owner.locator('.chat-message').count(),1);
 await owner.locator('#subject').selectOption('english');
 await owner.waitForFunction(()=>document.querySelector('#returnToLesson')?.getAttribute('href')?.includes('subject=english&flow=1'));
 assert.equal(await owner.locator('#returnToLesson').getAttribute('href'),'path.html?lesson=5&subject=english&flow=1');
 await owner.locator('#subject').selectOption('python');
 assert.equal(await owner.locator('#lesson option').count(),4,'Python only has four real workshop exercises');
 assert.deepEqual(errors,[],`Owner errors: ${errors.join('; ')}`);
 console.log('PASS: canonical-topic client, no request before click, scoped history, error recovery and Python bounds');
 await owner.close();
 const transfer=await browser.newPage();await transfer.route('**/vendor/supabase.js',route=>route.fulfill({status:200,contentType:'text/javascript',body:OWNER}));
 await transfer.route('**/functions/v1/academy-tutor',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({configured:true})}));
 await transfer.addInitScript(()=>sessionStorage.setItem('academy-tutor-transfer-v1',JSON.stringify({lesson:8,subject:'qa',text:'Мой тест-кейс с предусловием и ожидаемым результатом.'})));
 await transfer.goto(ROOT+'ai.html?lesson=8&subject=qa',{waitUntil:'domcontentloaded'});
 assert.equal(await transfer.locator('#question').inputValue(),'Мой тест-кейс с предусловием и ожидаемым результатом.');
 assert.equal(await transfer.locator('.mode[data-mode="review"]').getAttribute('aria-pressed'),'true');
 assert.equal(await transfer.evaluate(()=>sessionStorage.getItem('academy-tutor-transfer-v1')),null,'Imported draft removed from temporary transfer storage');
 assert.equal(await transfer.locator('.chat-message').count(),0,'Transfer never auto-sends');
 console.log('PASS: explicit lesson draft transfer requires review before user sends');await transfer.close();
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
